services:
  # Development service
  eber-fe-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Production service
  eber-fe-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # Production service with nginx (recommended for production)
  eber-fe-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    profiles:
      - nginx
