import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Box } from '@mui/material';
import ParticlesBackground from '@/components/BackgroundParticles';
import ThemeWrapper from '@/components/ThemeWrapper';

export const metadata: Metadata = {
  title: 'Eber Group',
  description: 'Generated by create next app',
};

const font = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-plus-jakarta-sans',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} ${font.variable} overflow-x-hidden overscroll-none`}
      >
        <ThemeWrapper>
          <Header />
          <Box className={`my-[10vh] px-[10vw]`}>
            <ParticlesBackground />
            {children}
          </Box>
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
