import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Box } from '@mui/material';
import ParticlesBackground from '@/components/BackgroundParticles';

export const metadata: Metadata = {
  title: 'Eber Group',
  description: 'Generated by create next app',
};

const font = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-Jakarta',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden overscroll-none">
        <Header />
        <Box className={`${font.variable} my-[10vh] px-[10vw]`}>
          <ParticlesBackground />
          {children}
        </Box>
        <Footer />
      </body>
    </html>
  );
}
